# 网站名称
site_name: Dev File

# 主题
theme:

  # 主题名字 - material
  name: material

  # 主题特征
  features:

    # 导航栏回到最上面按钮
    - navigation.top

    # 搜索建议
    - search.suggest

    # 搜索高亮
    - search.highlight

    # 搜索共享
    - search.share

  # 主题配色
  palette:

    # 明亮主题 - default
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: 切换暗黑主题

    # 暗黑主题 - slate
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: 切换明亮主题

# 扩展设置
extra:

  # 网站页脚
  social:

    # github
    - icon: fontawesome/brands/github
      link: https://github.com/XiangQinxi/

    # gitlab
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/XiangQinxi

    # bilibili
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/471425191

    # qq
    - icon: fontawesome/brands/qq
      link: tencent://message/?uin=1379773753


# 扩展主题
extra_css:
  - stylesheets/extra.css

# 额外插件
plugins:

  # 搜索插件
  - search

nav:
  - 主页: index.md

# markdown扩展插件
markdown_extensions:
  # 高级
  - admonition

  # 属性
  - attr_list

  # 代码块高亮显示
  - pymdownx.highlight:
      anchor_linenums: true

  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences


# 网站版权
copyright: Copyright &copy; 2022 XiangQinxi